import {modeFor,validMode,initialNotes,writingMode,languageFor} from '../../../lib/writing-settings';
import {imageFor,saveImage,reviewState,generateReview,explainChange,requireUnderstanding} from '../../../lib/draft-review';
import {classifyTopic,validTopic} from '../../../lib/vocabulary-topics';
import {vocabularyLibrary,vocabularyState,generatePack,readQuiz,quizPublic,submitQuiz,enforceReview,hasVocabulary} from '../../../lib/vocabulary';
import {db,own,messages,key,coach,coachDetailed,reportData,error} from '../../../lib/server';
import {authRoute,studentIdentity} from '../../../lib/student-auth';
import {teacherRoute} from '../../../lib/teacher-data';
import {requestOrigin} from '../../../lib/request-security';
export const dynamic='force-dynamic';
const json=(data:any,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function read(req:Request){try{const maximum=new URL(req.url).pathname.endsWith('/image')?1450000:200000;if(Number(req.headers.get('content-length')||0)>maximum)throw error('内容过长。',413);const text=await req.text();if(text.length>maximum)throw error('内容过长。',413);return JSON.parse(text);}catch(e:any){if(e.status)throw e;throw error('请求格式错误。');}}
function str(v:any,max:number){if(typeof v!=='string'||v.length>max)throw error('内容格式或长度不正确。');return v;}
function settings(b:any){if(!['IELTS','GRE','TOEFL'].includes(b.exam)||![10,20,30,40,60].includes(b.duration)||![120,150,200,250,400,600].includes(b.target))throw error('训练设置不正确。');const prompt=str(b.prompt,10000).trim();if(!prompt)throw error('请先添加题目。');const mode=b.writing_mode||modeFor(b.exam);if(!validMode(b.exam,mode)||mode==='ielts_task1'&&b.target<150)throw error('题型或字数目标不正确。');return {...b,prompt,writing_mode:mode,ui_language:languageFor(b.language??b.ui_language)};}
async function handle(req:Request,context:any){const {path}=await context.params;const now=Date.now();
 if(path[0]==='auth')return authRoute(req,path,read);
 if(path[0]==='teacher')return teacherRoute(req,path,read);
 const user=await studentIdentity(req);if(path[0]==='vocabulary'){if(path.length===1&&req.method==='GET')return json(await vocabularyLibrary(user));if(path[1]==='tests'&&path.length===3)return json({quiz:req.method==='GET'?quizPublic(await readQuiz(path[2],user)):await submitQuiz(path[2],user,await read(req))});throw error('找不到此接口。',404);}if(path[0]!=='sessions')throw error('找不到此接口。',404);
 if(path.length===1){if(req.method==='POST'){const b=settings(await read(req));const id=crypto.randomUUID();await db().prepare('INSERT INTO sessions (id,user_id,exam,prompt,writing_mode,ui_language,workflow_version,duration,target,stage,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,3,?,?,?,?,?,?)').bind(id,user,b.exam,b.prompt,b.writing_mode,b.ui_language,b.duration,b.target,'planning',JSON.stringify(initialNotes(b.writing_mode)),now,now).run();return json({session:await own(id,user)});}const history:any[]=(await db().prepare('SELECT * FROM sessions WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(user).all()).results;const session=history.length?await own(history[0].id,user):null;const r:any=session?await db().prepare('SELECT content FROM reports WHERE session_id=?').bind(session.id).first():null;return json({session,history:history.map(s=>({...s,notes:JSON.parse(s.notes)})),messages:session?await messages(session.id):[],report:r?JSON.parse(r.content):null,hasVocabulary:await hasVocabulary(user),coachMode:key()?'live':'unavailable'});}
 const id=path[1],s=await own(id,user);if(path.length===2){const r:any=await db().prepare('SELECT content FROM reports WHERE session_id=?').bind(id).first();return json({session:s,messages:await messages(id),report:r?JSON.parse(r.content):null,hasVocabulary:await hasVocabulary(user),coachMode:key()?'live':'unavailable'});}
 if(path[2]==='image'&&path.length===3){if(req.method==='POST')return json(await saveImage(s,await read(req)));if(req.method!=='GET')throw error('请求方法不正确。',405);const image=await imageFor(s.id);return json({image:image?{dataUrl:image.image_data,mimeType:image.mime_type,bytes:image.byte_size}:null});}
 if(path[2]==='review'&&path.length===3){if(req.method==='POST'){const body=await read(req);if(!['draft','final'].includes(body.kind))throw error('点评类型不正确。');await generateReview(s,body.kind);}return json(await reviewState(s));}
 if(path[2]==='explain'&&path.length===3&&req.method==='POST'){await explainChange(s,await read(req));return json(await reviewState(s));}
 if(path[2]==='vocabulary'&&path.length===3){if(req.method==='POST')await generatePack(s,user);return json(await vocabularyState(s,user));}
 if(req.method!=='POST')throw error('请求方法不正确。',405);const b=await read(req),action=path[2];
 if(action==='language'){if(!['zh','en'].includes(b.language))throw error('语言选项不正确。');await db().prepare('UPDATE sessions SET ui_language=? WHERE id=?').bind(b.language,id).run();return json({session:await own(id,user)});}
 if(action==='configure'){if(s.stage!=='planning')throw error('计时开始后不能更改题目和训练设置。',409);const v=settings(b);if(b.topic_type!==undefined&&!validTopic(b.topic_type))throw error('主题类型不正确。');const topic=b.topic_type??(v.prompt===s.prompt?s.topic_type:classifyTopic(v.prompt));await db().prepare('UPDATE sessions SET exam=?,prompt=?,writing_mode=?,ui_language=?,duration=?,target=?,topic_type=?,updated_at=? WHERE id=? AND stage=?').bind(v.exam,v.prompt,v.writing_mode,v.ui_language,v.duration,v.target,topic,now,id,'planning').run();return json({session:await own(id,user)});}
 if(action==='save'){if(s.stage==='complete')throw error('这次练习已经完成。',409);const draft=str(b.draft,60000),reflection=str(b.reflection||'',5000);if(s.workflow_version===3&&['polishing','reviewing'].includes(s.stage)&&draft!==s.draft)throw error('请先进入自主润色，或返回修改后再编辑正文。',409);if(s.stage==='planning'&&draft)throw error('请先开始计时写作。');const notes:any={...s.notes};for(const name of ['claim','reason','example','features','directImpact','affectedGroup','indirectImpact','reason1','reason2','rebuttal'])if(b.notes?.[name]!==undefined)notes[name]=str(b.notes[name],5000);const ev=Array.isArray(b.events)?b.events:[];if(ev.length>3000)throw error('记录过多，请分批保存。');const statements=[db().prepare('UPDATE sessions SET draft=?,notes=?,reflection=?,updated_at=? WHERE id=? AND stage=?').bind(draft,JSON.stringify(notes),reflection,now,id,s.stage)];if(draft!==s.draft)statements.push(db().prepare('INSERT INTO snapshots (id,session_id,stage,content,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,s.stage,draft,now));for(const e of ev){if(!['edit','paste','focus_out'].includes(e.type)||!Number.isFinite(e.at))continue;str(e.id,80);statements.push(db().prepare('INSERT OR IGNORE INTO events (id,session_id,type,stage,client_at,received_at,detail) VALUES (?,?,?,?,?,?,?)').bind(e.id,id,e.type,s.stage,e.at,now,JSON.stringify(e.detail||{}).slice(0,1000)));}await db().batch(statements);return json({saved:true});}
 if(action==='chat'){if(s.stage==='complete')throw error('练习已完成，可开始新的练习。',409);const question=str(b.question,4000).trim(),requestId=str(b.requestId,80);if(!question)throw error('请先输入问题。');const history:any[]=await messages(id);if(history.length>=120)throw error('本次对话已达到上限，请完成修改或开始新练习。');if(history.some(m=>m.id===requestId))return json({messages:history,coachMode:'live'});let slot:number|null=null;if(s.stage==='writing'){slot=Math.floor((now-s.started_at)/600000);if(slot<1)throw error('写作满十分钟后可以提问。',403);}const quota=s.stage==='writing'?`writing:${slot}`:`request:${requestId}`;try{await db().prepare('INSERT INTO ai_slots (session_id,slot,request_id,created_at) VALUES (?,?,?,?)').bind(id,quota,requestId,now).run();}catch{throw error('本次提问机会已使用，等待下一个十分钟节点。',409);}try{const answer=await coachDetailed(s,question,history);const content=answer.content;const latest=await own(id,user);if(latest.stage!==s.stage)throw error('写作阶段已经变化，请重新提问。',409);await db().batch([db().prepare('INSERT INTO messages (id,session_id,role,content,stage,slot,created_at,mode) VALUES (?,?,?,?,?,?,?,?)').bind(requestId,id,'user',question,s.stage,slot,now,'live'),db().prepare('INSERT INTO messages (id,session_id,role,content,stage,slot,created_at,mode,translations_json) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,'assistant',content,s.stage,slot,now+1,'live',JSON.stringify(answer.translations))]);return json({messages:await messages(id),coachMode:'live'});}catch(e){await db().prepare('DELETE FROM ai_slots WHERE session_id=? AND slot=? AND request_id=?').bind(id,quota,requestId).run();throw e;}}
 if(action==='refresh-report'){if(s.stage!=='complete')throw error('报告尚未完成。',409);const report=await reportData(s);await db().prepare('UPDATE reports SET content=?,created_at=? WHERE session_id=?').bind(JSON.stringify(report),now,id).run();return json({session:s,report});}
 if(action==='transition'){if(s.workflow_version===3&&b.action==='revise-again'){if(s.stage!=='reviewing')throw error('当前阶段不能返回润色。',409);await db().prepare("UPDATE sessions SET stage='revising',updated_at=? WHERE id=? AND stage='reviewing'").bind(now,id).run();return json({session:await own(id,user)});}const next:any={start:['planning','writing'],finish:['writing','polishing'],analyze:['polishing','revising'],report:[s.workflow_version===3?'reviewing':'revising','complete'],'submit-revision':['revising','reviewing']};const rule=next[b.action];if(!rule||s.stage!==rule[0])throw error('当前阶段不支持这个操作。',409);if(b.action==='start'){if(writingMode(s)==='ielts_task1'&&!await imageFor(s.id))throw error('请先上传雅思小作文图片，再开始写作。',409);await enforceReview(s,user);}if(b.action==='analyze'&&s.workflow_version===3)await requireUnderstanding(s,'draft');if(b.action==='submit-revision'){if(s.workflow_version!==3)throw error('这篇旧版练习沿用原提交流程。',409);await generateReview(s,'final');}if(b.action==='report'&&s.workflow_version===3)await requireUnderstanding(s,'final');if(b.action!=='start'&&!s.draft.trim())throw error('请先完成作文。');let report:any=null,analysisMessage:string|null=null,aiWarning:string|null=null;if(b.action==='analyze'&&s.workflow_version!==3){try{analysisMessage=await coach(s,'请引用我的草稿中一个具体问题，并追问我可以怎样自主修改。',await messages(id));}catch(e:any){if(e.status!==503)throw e;aiWarning=e.message+' 你可以先自主修改，完成过程报告后再补充 AI 分析。';}}if(b.action==='report')report=await reportData(s);if(['analyze','report','submit-revision'].includes(b.action)){const latest=await own(id,user);if(latest.stage!==s.stage||latest.updated_at!==s.updated_at)throw error('作文在分析过程中发生了变化，请重新提交。',409);}const statements=[];const field=b.action==='start'?'started_at':b.action==='finish'?'finished_at':['analyze','submit-revision'].includes(b.action)?'submitted_at':'completed_at';statements.push(db().prepare(`UPDATE sessions SET stage=?, ${field}=?, updated_at=?${b.action==='finish'?', original=draft':''} WHERE id=? AND stage=?`).bind(rule[1],now,now,id,rule[0]));if(analysisMessage)statements.push(db().prepare('INSERT INTO messages (id,session_id,role,content,stage,created_at,mode) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,'assistant',analysisMessage,'revising',now,'live'));if(report)statements.push(db().prepare('INSERT INTO reports (session_id,content,created_at) VALUES (?,?,?) ON CONFLICT(session_id) DO UPDATE SET content=excluded.content,created_at=excluded.created_at').bind(id,JSON.stringify(report),now));await db().batch(statements);return json({session:await own(id,user),report,aiWarning,messages:await messages(id)});}
 throw error('找不到此操作。',404);
}
export async function GET(req:Request,c:any){try{return await handle(req,c);}catch(e:any){console.error('WRTBU request error',e.status||500);return json({error:e.status?e.message:'数据服务暂时不可用，输入已保留。'},e.status||503);}}
export async function POST(req:Request,c:any){try{const origin=req.headers.get('Origin');if(origin!==requestOrigin(req)||!req.headers.get('Content-Type')?.toLowerCase().startsWith('application/json'))throw error('请求来源不正确。',403);return await handle(req,c);}catch(e:any){console.error('WRTBU request error',e.status||500);return json({error:e.status?e.message:'服务暂时不可用，输入已保留。'},e.status||503);}}
