import {db,own,messages,key,coach,reportData,error} from '../../../lib/server';
import {authRoute,studentIdentity} from '../../../lib/student-auth';
import {teacherRoute} from '../../../lib/teacher-data';
export const dynamic='force-dynamic';
const json=(data:any,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function read(req:Request){try{if(Number(req.headers.get('content-length')||0)>200000)throw error('内容过长。',413);const text=await req.text();if(text.length>200000)throw error('内容过长。',413);return JSON.parse(text);}catch(e:any){if(e.status)throw e;throw error('请求格式错误。');}}
function str(v:any,max:number){if(typeof v!=='string'||v.length>max)throw error('内容格式或长度不正确。');return v;}
function settings(b:any){if(!['IELTS','GRE','TOEFL'].includes(b.exam)||![10,20,30,40,60].includes(b.duration)||![120,250,400,600].includes(b.target))throw error('训练设置不正确。');const prompt=str(b.prompt,10000).trim();if(!prompt)throw error('请先添加题目。');return {...b,prompt};}
async function handle(req:Request,context:any){const {path}=await context.params;const now=Date.now();
 if(path[0]==='auth')return authRoute(req,path,read);
 if(path[0]==='teacher')return teacherRoute(req,path,read);
 const user=await studentIdentity(req);if(path[0]!=='sessions')throw error('找不到此接口。',404);
 if(path.length===1){if(req.method==='POST'){const b=settings(await read(req));const id=crypto.randomUUID();await db().prepare('INSERT INTO sessions (id,user_id,exam,prompt,duration,target,stage,notes,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(id,user,b.exam,b.prompt,b.duration,b.target,'planning',JSON.stringify({claim:'',reason:'',example:''}),now,now).run();return json({session:await own(id,user)});}const history:any[]=(await db().prepare('SELECT * FROM sessions WHERE user_id=? ORDER BY created_at DESC LIMIT 100').bind(user).all()).results;const session=history.length?await own(history[0].id,user):null;const r:any=session?await db().prepare('SELECT content FROM reports WHERE session_id=?').bind(session.id).first():null;return json({session,history:history.map(s=>({...s,notes:JSON.parse(s.notes)})),messages:session?await messages(session.id):[],report:r?JSON.parse(r.content):null,coachMode:key()?'live':'unavailable'});}
 const id=path[1],s=await own(id,user);if(path.length===2){const r:any=await db().prepare('SELECT content FROM reports WHERE session_id=?').bind(id).first();return json({session:s,messages:await messages(id),report:r?JSON.parse(r.content):null,coachMode:key()?'live':'unavailable'});}
 if(req.method!=='POST')throw error('请求方法不正确。',405);const b=await read(req),action=path[2];
 if(action==='configure'){if(s.stage!=='planning')throw error('计时开始后不能更改题目和训练设置。',409);const v=settings(b);await db().prepare('UPDATE sessions SET exam=?,prompt=?,duration=?,target=?,updated_at=? WHERE id=? AND stage=?').bind(v.exam,v.prompt,v.duration,v.target,now,id,'planning').run();return json({session:await own(id,user)});}
 if(action==='save'){if(s.stage==='complete')throw error('这次练习已经完成。',409);const draft=str(b.draft,60000),reflection=str(b.reflection||'',5000);if(s.stage==='planning'&&draft)throw error('请先开始计时写作。');const notes={claim:str(b.notes?.claim||'',5000),reason:str(b.notes?.reason||'',5000),example:str(b.notes?.example||'',5000)};const ev=Array.isArray(b.events)?b.events:[];if(ev.length>3000)throw error('记录过多，请分批保存。');const statements=[db().prepare('UPDATE sessions SET draft=?,notes=?,reflection=?,updated_at=? WHERE id=? AND stage=?').bind(draft,JSON.stringify(notes),reflection,now,id,s.stage)];if(draft!==s.draft)statements.push(db().prepare('INSERT INTO snapshots (id,session_id,stage,content,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,s.stage,draft,now));for(const e of ev){if(!['edit','paste','focus_out'].includes(e.type)||!Number.isFinite(e.at))continue;str(e.id,80);statements.push(db().prepare('INSERT OR IGNORE INTO events (id,session_id,type,stage,client_at,received_at,detail) VALUES (?,?,?,?,?,?,?)').bind(e.id,id,e.type,s.stage,e.at,now,JSON.stringify(e.detail||{}).slice(0,1000)));}await db().batch(statements);return json({saved:true});}
 if(action==='chat'){if(s.stage==='complete')throw error('练习已完成，可开始新的练习。',409);const question=str(b.question,4000).trim(),requestId=str(b.requestId,80);if(!question)throw error('请先输入问题。');const history:any[]=await messages(id);if(history.length>=120)throw error('本次对话已达到上限，请完成修改或开始新练习。');if(history.some(m=>m.id===requestId))return json({messages:history,coachMode:'live'});let slot:number|null=null;if(s.stage==='writing'){slot=Math.floor((now-s.started_at)/600000);if(slot<1)throw error('写作满十分钟后可以提问。',403);}const quota=s.stage==='writing'?`writing:${slot}`:`request:${requestId}`;try{await db().prepare('INSERT INTO ai_slots (session_id,slot,request_id,created_at) VALUES (?,?,?,?)').bind(id,quota,requestId,now).run();}catch{throw error('本次提问机会已使用，等待下一个十分钟节点。',409);}try{const content=await coach(s,question,history);const latest=await own(id,user);if(latest.stage!==s.stage)throw error('写作阶段已经变化，请重新提问。',409);await db().batch([db().prepare('INSERT INTO messages (id,session_id,role,content,stage,slot,created_at,mode) VALUES (?,?,?,?,?,?,?,?)').bind(requestId,id,'user',question,s.stage,slot,now,'live'),db().prepare('INSERT INTO messages (id,session_id,role,content,stage,slot,created_at,mode) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,'assistant',content,s.stage,slot,now+1,'live')]);return json({messages:await messages(id),coachMode:'live'});}catch(e){await db().prepare('DELETE FROM ai_slots WHERE session_id=? AND slot=? AND request_id=?').bind(id,quota,requestId).run();throw e;}}
 if(action==='refresh-report'){if(s.stage!=='complete')throw error('报告尚未完成。',409);const report=await reportData(s);await db().prepare('UPDATE reports SET content=?,created_at=? WHERE session_id=?').bind(JSON.stringify(report),now,id).run();return json({session:s,report});}
 if(action==='transition'){const next:any={start:['planning','writing'],finish:['writing','polishing'],analyze:['polishing','revising'],report:['revising','complete']};const rule=next[b.action];if(!rule||s.stage!==rule[0])throw error('当前阶段不支持这个操作。',409);if(b.action!=='start'&&!s.draft.trim())throw error('请先完成作文。');let report:any=null,analysisMessage:string|null=null,aiWarning:string|null=null;if(b.action==='analyze'){try{analysisMessage=await coach(s,'请引用我的草稿中一个具体问题，并追问我可以怎样自主修改。',await messages(id));}catch(e:any){if(e.status!==503)throw e;aiWarning=e.message+' 你可以先自主修改，完成过程报告后再补充 AI 分析。';}}if(b.action==='report')report=await reportData(s);if(b.action==='analyze'||b.action==='report'){const latest=await own(id,user);if(latest.stage!==s.stage||latest.updated_at!==s.updated_at)throw error('作文在分析过程中发生了变化，请重新提交。',409);}const statements=[];const field=b.action==='start'?'started_at':b.action==='finish'?'finished_at':b.action==='analyze'?'submitted_at':'completed_at';statements.push(db().prepare(`UPDATE sessions SET stage=?, ${field}=?, updated_at=?${b.action==='finish'?', original=draft':''} WHERE id=? AND stage=?`).bind(rule[1],now,now,id,rule[0]));if(analysisMessage)statements.push(db().prepare('INSERT INTO messages (id,session_id,role,content,stage,created_at,mode) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,'assistant',analysisMessage,'revising',now,'live'));if(report)statements.push(db().prepare('INSERT INTO reports (session_id,content,created_at) VALUES (?,?,?) ON CONFLICT(session_id) DO UPDATE SET content=excluded.content,created_at=excluded.created_at').bind(id,JSON.stringify(report),now));await db().batch(statements);return json({session:await own(id,user),report,aiWarning,messages:await messages(id)});}
 throw error('找不到此操作。',404);
}
export async function GET(req:Request,c:any){try{return await handle(req,c);}catch(e:any){console.error('WRTBU request error',e.status||500);return json({error:e.status?e.message:'数据服务暂时不可用，输入已保留。'},e.status||503);}}
export async function POST(req:Request,c:any){try{const origin=req.headers.get('Origin');if(origin!==new URL(req.url).origin||!req.headers.get('Content-Type')?.toLowerCase().startsWith('application/json'))throw error('请求来源不正确。',403);return await handle(req,c);}catch(e:any){console.error('WRTBU request error',e.status||500);return json({error:e.status?e.message:'服务暂时不可用，输入已保留。'},e.status||503);}}
