'use client';
import {useLanguage,LanguageSwitcher} from './language';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Check,ChevronLeft,ChevronRight,LoaderCircle,RefreshCw} from 'lucide-react';
import {api} from '../lib/client';
import {LEARNING_ROLES} from '../lib/vocabulary-personalization';
import {VOCABULARY_TOPICS,topicLabel} from '../lib/vocabulary-topics';
const percent=(n:any,total:number)=>typeof n==='number'&&total?Math.round(n/total*100)+'%':'待完成';
const date=(n:number)=>new Date(n).toLocaleDateString(typeof document!=='undefined'?document.documentElement.lang:'zh-CN');

export function WordCards({items}:{items:any[]}){
 const {t,language}=useLanguage();return <div className="vocabulary-cards">{items.map((item,i)=><article className="vocabulary-word" key={item.term}><header><span>{t(String(i+1).padStart(2,'0'))}</span><small>{t(item.kind==='phrase'?'词组':'单词')} · {t(item.partOfSpeech)}</small></header><h3 lang="en">{t(item.term)}</h3>{item.learningRole&&<span className={'vocabulary-role '+item.learningRole}>{t(LEARNING_ROLES[item.learningRole as keyof typeof LEARNING_ROLES])}</span>}<p className="vocabulary-meaning">{language==='en'?(item.meaningEn||item.meaning):item.meaning}</p><p>{language==='en'?(item.reasonEn||item.reason):item.reason}</p><div className="vocabulary-question">{language==='en'?(item.questionEn||item.question):item.question}</div></article>)}</div>;}

export function TestRunner({quiz:initial,onUpdate,onClose}:{quiz:any;onUpdate?:(q:any)=>void;onClose?:()=>void}){
 const {t,language}=useLanguage();
 const [quiz,setQuiz]=useState(initial),[answers,setAnswers]=useState<Record<string,string>>({}),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const storage='wrtbu-v2-test:'+quiz.id+':'+quiz.phase;
 useEffect(()=>{setQuiz(initial);},[initial]);
 useEffect(()=>{setPage(0);try{const saved=JSON.parse(localStorage.getItem(storage)||'{}');setAnswers(saved&&typeof saved==='object'?saved:{});}catch{setAnswers({});}},[storage]);
 function answer(id:string,value:string){setAnswers(old=>{const next={...old,[id]:value};try{localStorage.setItem(storage,JSON.stringify(next));}catch{}return next;});}
 async function submit(){setBusy(true);setError('');try{const d=await api('vocabulary/tests/'+quiz.id,{phase:quiz.phase,answers});try{localStorage.removeItem(storage);}catch{}setQuiz(d.quiz);onUpdate?.(d.quiz);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const questions=quiz.questions||[],answered=questions.filter((q:any)=>answers[q.id]?.trim()).length,complete=quiz.phase==='complete',pages=Math.ceil(quiz.count/10);
 return <section className="vocabulary-test"><div className="vocabulary-heading"><div><p className="eyebrow">{t(quiz.kind==='milestone'?(language==='en'?`Milestone test ${quiz.batchNumber}`:`第 ${quiz.batchNumber} 次阶段大测`):'写作前 · 主题复习')}</p><h2>{t(complete?'本次测试结果':quiz.phase==='choice'?'先辨词义，再回忆拼写':'接下来，自己拼出来')}</h2><p>{t(quiz.count)} {t("项")}{t(quiz.kind==='milestone'&&quiz.count<100?' · 前十次词汇去重后不足 100 项，本次考察全部不同词语':'')} · {t(complete?'两部分分别记录正确率':quiz.phase==='choice'?'第一部分：选择题':'第二部分：拼写填词')}</p></div>{onClose&&<button className="button light" onClick={onClose}>{t("收起测试")}</button>}</div>
 {error&&<p className="auth-error" role="alert">{t(error)}</p>}
 {complete?<><div className="vocabulary-results"><span>{t("选择题")}<strong>{t(percent(quiz.choiceScore,quiz.count))}</strong> {t(quiz.choiceScore)}/{t(quiz.count)}</span><span>{t("拼写题")}<strong>{t(percent(quiz.spellingScore,quiz.count))}</strong> {t(quiz.spellingScore)}/{t(quiz.count)}</span></div><p className="muted">{t("先区分词义，再遮住答案回忆拼写。词组也要检查介词、单复数和词序。")}</p><div className="vocabulary-table-scroll"><table className="vocabulary-table"><thead><tr><th>{t("词语 / 含义")}</th><th>{t("选择题")}</th><th>{t("你的拼写")}</th></tr></thead><tbody>{questions.map((q:any)=><tr key={q.id}><td><b>{t(q.term)}</b><small>{language==='en'?(q.meaningEn||q.meaning):q.meaning}</small></td><td><span className={q.choiceCorrect?'answer-correct':'answer-wrong'}>{t(q.choiceCorrect?'正确':q.choiceAnswer+' · 错误')}</span></td><td><span className={q.spellingCorrect?'answer-correct':'answer-wrong'}>{t(q.spellingAnswer)} · {t(q.spellingCorrect?'正确':'需复习')}</span></td></tr>)}</tbody></table></div></>:<><div className="vocabulary-test-progress"><span>{t("已作答")}{t(answered)} / {t(quiz.count)}</span><span>{t(page+1)} / {t(pages)} {t("页")}</span></div><div className="word-progress"><div style={{width:answered/quiz.count*100+'%'}}/></div><div className="vocabulary-questions">{questions.slice(page*10,page*10+10).map((q:any,i:number)=><fieldset key={q.id}><legend><span>{t(page*10+i+1)}.</span> {language==='en'?(q.meaningEn||q.meaning):q.meaning} <small>{t(q.kind==='phrase'?'词组':'单词')}</small></legend>{quiz.phase==='choice'?<div className="vocabulary-options">{q.options.map((o:any,j:number)=><label key={o.id} className={answers[q.id]===o.id?'selected':''}><input type="radio" name={q.id} value={o.id} checked={answers[q.id]===o.id} onChange={()=>answer(q.id,o.id)} disabled={busy}/><span>{t(String.fromCharCode(65+j))}</span>{t(o.text)}</label>)}</div>:<input className="vocabulary-spelling" aria-label={t('第 '+(page*10+i+1)+' 题拼写')} lang="en" autoComplete="off" autoCorrect="off" autoCapitalize="none" spellCheck={false} placeholder={t(q.kind==='phrase'?'填写完整英文词组':'填写英文单词')} value={answers[q.id]||''} disabled={busy} onChange={e=>answer(q.id,e.target.value)}/>}</fieldset>)}</div><div className="vocabulary-test-footer"><div><button className="button light" disabled={page===0||busy} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/>{t("上一页")}</button><button className="button light" disabled={page>=pages-1||busy} onClick={()=>setPage(p=>p+1)}>{t("下一页")}<ChevronRight size={16}/></button></div><button className="button primary" disabled={busy||answered!==quiz.count} onClick={submit}>{busy?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>} {t(quiz.phase==='choice'?'完成选择题，进入拼写':'提交拼写，查看结果')}</button></div>{quiz.phase==='spelling'&&<p className="muted">{t("选择题得分：")}{t(quiz.choiceScore)}/{t(quiz.count)}{t("。全部拼写完成后显示逐题结果。")}</p>}</>}
 </section>;
}

export function VocabularyWarmup({session,onReady,onTopic,hasVocabulary}:{session:any;hasVocabulary:boolean;onReady:(key:string,ready:boolean)=>void;onTopic:(topic:string)=>void}){
 const {t,language}=useLanguage();
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);const sequence=useRef(0);const key=session.id+':'+session.topic_type;
 async function load(){const seq=++sequence.current;setLoading(true);setError('');onReady(key,false);try{const d=await api('sessions/'+session.id+'/vocabulary');if(seq!==sequence.current)return;setData(d);onReady(key,!d.review||d.review.phase==='complete');}catch(e:any){if(seq===sequence.current)setError(e.message);}finally{if(seq===sequence.current)setLoading(false);}}
 useEffect(()=>{setData(null);load();return()=>{sequence.current++;};},[key]);
 if(!hasVocabulary&&data&&!data.review)return null;
 return <section className="vocabulary-warmup"><div className="vocabulary-heading"><div><p className="eyebrow">{t("WRTBU 03 · 词汇准备")}</p><h2>{t("带着上一次学到的表达，开始这一次写作")}</h2><p>{t("同主题再次练习时，先做 10 项选择题，再完成 10 项拼写。复习期间尚未开始写作计时。")}</p></div><label className="vocabulary-topic">{t("题目主题")}<select aria-label={t("题目主题")} value={session.topic_type||'general'} onChange={e=>onTopic(e.target.value)}>{VOCABULARY_TOPICS.map(topic=><option key={topic.id} value={topic.id}>{t(topic.label)}</option>)}</select></label></div>{loading?<p role="status" className="muted">{t("正在读取这个主题的学习记录…")}</p>:error?<div><p className="auth-error" role="alert">{t(error)}</p><button className="button light" onClick={load}><RefreshCw size={16}/>{t("重新读取")}</button></div>:data?.review?<>{data.review.phase==='complete'?<div className="vocabulary-review-done"><p><Check size={17}/>{t("课前复习已完成 · 选择")}{t(data.review.choiceScore)}/{t(data.review.count)} {t("· 拼写")}{t(data.review.spellingScore)}/{t(data.review.count)}{t("。现在可以开始写作。")}</p><details><summary>{t("查看复习结果")}</summary><TestRunner key={data.review.id} quiz={data.review}/></details></div>:<TestRunner key={data.review.id} quiz={data.review} onUpdate={q=>{setData((d:any)=>({...d,review:q}));onReady(key,q.phase==='complete');}}/>}</>:<div className="vocabulary-first"><BookOpen size={21}/><p>{t("这是你第一次学习「")}{t(topicLabel(session.topic_type))}{t("」主题。先完成写作，报告中会为你推荐 20 个单词与词组；下一次同主题练习再复习。")}</p></div>}</section>;
}

function Adaptation({pack}:{pack:any}){
 const {t,language}=useLanguage();const a=pack.personalization?.adaptation,counts=pack.personalization?.roleCounts;return a?<div className="vocabulary-adaptation"><h3>{t("这组表达，为什么适合你")}</h3><p>{language==='en'?(a.focusEn||a.focus):a.focus}</p>{counts&&<div className="vocabulary-role-counts"><span>{t("巩固基础")}{t(counts.consolidate)}</span><span>{t("拓展表达")}{t(counts.extend)}</span><span>{t("适度挑战")}{t(counts.challenge)}</span></div>}<details><summary>{t("查看本篇作文中的依据")}</summary>{a.evidence.map((e:any,i:number)=><div key={i}><blockquote>{t(e.quote)}</blockquote><p>{language==='en'?(e.observationEn||e.observation):e.observation}</p></div>)}</details><small>{t("针对本篇练习安排学习方向，会随你的写作与测试结果调整。")}</small></div>:null;}

export function VocabularyProfile({data}:{data:any}){
 const {t,language}=useLanguage();const s=data.stats;return <div className="vocabulary-profile"><div className="vocabulary-stats">{[['学习词语',s.uniqueTerms+' 项'],['领取词汇',s.practices+' 次'],['选择题正确率',s.choiceAccuracy===null?'待测试':s.choiceAccuracy+'%'],['拼写正确率',s.spellingAccuracy===null?'待测试':s.spellingAccuracy+'%']].map(([label,value])=><div key={label}><span>{t(label)}</span><strong>{t(value)}</strong></div>)}</div><p>{language==='en'?data.summaryEn||data.summary:data.summary}</p>{data.errors.length>0&&<details open><summary>{t("需要多练几次的词语")}</summary><div className="vocabulary-error-list">{data.errors.map((e:any)=><article key={e.term}><b>{t(e.term)}</b><span>{language==='en'?(e.meaningEn||e.meaning):e.meaning}</span><small>{t("选择错误")}{t(e.choiceErrors)} {t("次 · 拼写错误")}{t(e.spellingErrors)} {t("次 · 共")}{t(e.attempts)} {t("次作答")}</small><p>{t(e.nextStep)}</p></article>)}</div></details>}<small className="muted">{t("按已提交的词汇测试统计，反映当前记录；更新时间")}{t(new Date(data.refreshedAt).toLocaleString(typeof document!=='undefined'?document.documentElement.lang:'zh-CN'))}。</small></div>;}

export function VocabularyReport({session,onLearned}:{session:any;onLearned?:()=>void}){
 const {t,language}=useLanguage();
 const [data,setData]=useState<any>(null),[profile,setProfile]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[active,setActive]=useState<any>(null);const seq=useRef(0);
 async function load(recommend=false){const n=++seq.current;setBusy(true);setError('');try{let d=await api('sessions/'+session.id+'/vocabulary');if(n!==seq.current)return;if(!d.pack&&recommend&&!d.generating)d=await api('sessions/'+session.id+'/vocabulary',{});const p=await api('vocabulary');if(n!==seq.current)return;setData(d);setProfile(p);if(d.pack)onLearned?.();}catch(e:any){if(n===seq.current)setError(e.message);}finally{if(n===seq.current)setBusy(false);}}
 useEffect(()=>{setData(null);setProfile(null);setActive(null);load(true);return()=>{seq.current++;};},[session.id]);
 useEffect(()=>{if(!data?.generating)return;const timer=setTimeout(()=>load(true),4000);return()=>clearTimeout(timer);},[data]);
 return <section className="report-section vocabulary-report"><div className="vocabulary-heading"><div><p className="eyebrow">{t("把表达留给下一次练习")}</p><h2>{t("本次主题词汇与个人词汇报告")}</h2><p>{t("根据这篇作文的实际用词、句子、修改和测试记录，为你安排难度合适的 20 个单词与词组。")}</p></div></div>{(busy||data?.generating)&&<p role="status" className="muted"><LoaderCircle size={16} className="spin"/> {t("正在整理学习词汇…")}</p>}{error&&<p role="alert" className="auth-error">{t(error)} {t("作文与报告已保存，可稍后再领取词汇。")}</p>}{!busy&&!data?.pack&&!data?.generating&&<button className="button primary" onClick={()=>load(true)}><RefreshCw size={16}/>{t("领取主题词汇")}</button>}{data?.pack&&<><p className="vocabulary-summary">{language==='en'?data.pack.personalization.summaryEn||data.pack.personalization.summary:data.pack.personalization.summary}</p><Adaptation pack={data.pack}/><WordCards items={data.pack.items}/></>}{data?.review?.phase==='complete'&&<p className="vocabulary-summary">{t("本次写作前复习：选择题")}{t(data.review.choiceScore)}/{t(data.review.count)}（{t(percent(data.review.choiceScore,data.review.count))}{t("），拼写")}{t(data.review.spellingScore)}/{t(data.review.count)}（{t(percent(data.review.spellingScore,data.review.count))}）。</p>}{data?.pendingMilestones?.map((q:any)=><div className="vocabulary-milestone" key={q.id}><div><h3>{t("已完成第")}{t(q.batchNumber*10)} {t("次词汇学习，阶段大测已准备好")}</h3><p>{t("从对应十次练习的词汇中去重抽取")}{t(q.count)} {t("项，先选择再拼写")}{t(q.count<100?'；不足 100 个不同词语，本次考察全部不同词语':'')}。</p></div><button className="button primary" onClick={()=>setActive(q)}>{t("开始大测")}</button></div>)}{active&&<TestRunner key={active.id} quiz={active} onClose={()=>setActive(null)} onUpdate={q=>{setActive(q);if(q.phase==='complete')load();}}/>}{profile&&<><h3 className="vocabulary-profile-title">{t("你的词汇学习画像")}</h3><VocabularyProfile data={profile}/></>}</section>;
}

export function VocabularyLibrary(){
 const {t,language}=useLanguage();
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[active,setActive]=useState<any>(null);
 async function load(){try{setData(await api('vocabulary'));setError('');}catch(e:any){setError(e.message);}}
 useEffect(()=>{load();},[]);
 return <div className="vocabulary-library">{error&&<p className="auth-error" role="alert">{t(error)}</p>}{!data?<p className="muted">{t("正在读取词汇记录…")}</p>:<><section className="report-section"><div className="vocabulary-heading"><div><p className="eyebrow">{t("20 个表达 · 一次小练习")}</p><h2>{t("把学过的词语，变成自己的表达")}</h2><p>{t("每十次领取词汇触发一次阶段大测。选择题和拼写题分别统计。")}</p></div><button className="button light" onClick={load}><RefreshCw size={16}/>{t("刷新")}</button></div><VocabularyProfile data={data}/></section>{active&&<TestRunner key={active.id} quiz={active} onClose={()=>setActive(null)} onUpdate={q=>{setActive(q);if(q.phase==='complete')load();}}/>}<section className="report-section"><h3>{t("测试记录")}</h3>{data.tests.length?data.tests.map((q:any)=><button className="vocabulary-test-row" key={q.id} onClick={()=>setActive(q)}><div><b>{t(q.kind==='milestone'?`第 ${q.batchNumber} 次阶段大测`:q.topicLabel+' · 课前复习')}</b><span>{t(q.count)} {t("项 ·")}{t(date(q.createdAt))} · {t(q.phase==='complete'?'已完成':q.phase==='spelling'?'待完成拼写':'待完成选择题')}</span></div><span>{t("选择")}{t(percent(q.choiceScore,q.count))} {t("· 拼写")}{t(percent(q.spellingScore,q.count))}</span><ChevronRight size={16}/></button>):<p className="muted">{t("首次学习先领取词汇，下次同主题练习会出现课前复习。")}</p>}</section><section className="report-section"><h3>{t("每次学过的单词与词组")}</h3>{data.packs.map((p:any)=><details className="vocabulary-pack" key={p.session_id}><summary>{t("第")}{t(p.practice_number)} {t("次 ·")}{t(p.exam)} · {t(topicLabel(p.topic_type))} · {t(p.items.length)} {t("项")}<small>{t(date(p.created_at))}</small></summary><p>{t(p.prompt)}</p><p className="muted">{t(p.personalization.summary)}</p><Adaptation pack={p}/><WordCards items={p.items}/></details>)}{!data.packs.length&&<p className="muted">{t("完成作文并生成报告后，会在这里保存第一组词汇。")}</p>}</section></>}</div>;
}

export function TeacherVocabulary({studentId}:{studentId:string}){
 const {t,language}=useLanguage();
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;const load=async()=>{try{const d=await api('teacher/vocabulary/'+studentId);if(alive){setData(d);setError('');}}catch(e:any){if(alive)setError(e.message);}};setData(null);load();const t=setInterval(load,30000);return()=>{alive=false;clearInterval(t);};},[studentId]);
 return <section className="teacher-card vocabulary-teacher"><h2>{t("词汇与词组学习记录")}</h2>{error&&<p className="auth-error">{t(error)}</p>}{data?<><VocabularyProfile data={data}/><h3 className="vocabulary-profile-title">{t("每次测试正确率")}</h3><div className="vocabulary-table-scroll"><table className="vocabulary-table"><thead><tr><th>{t("测试 / 数量")}</th><th>{t("日期")}</th><th>{t("选择题")}</th><th>{t("拼写题")}</th></tr></thead><tbody>{data.tests.map((q:any)=><tr key={q.id}><td>{t(q.kind==='milestone'?`阶段大测 ${q.batchNumber}`:q.topicLabel+'复习')} · {t(q.count)} {t("项")}</td><td>{t(date(q.createdAt))}</td><td>{t(percent(q.choiceScore,q.count))}</td><td>{t(percent(q.spellingScore,q.count))}</td></tr>)}</tbody></table></div><h3 className="vocabulary-profile-title">{t("每次学过的词语")}</h3>{data.packs.map((p:any)=><details className="vocabulary-pack" key={p.session_id}><summary>{t("第")}{t(p.practice_number)} {t("次 ·")}{t(p.exam)} · {t(topicLabel(p.topic_type))} · {t(p.items.length)} {t("项")}</summary><p>{t(p.prompt)}</p><Adaptation pack={p}/><WordCards items={p.items}/><details className="vocabulary-source-audit"><summary>{t("后台来源核验记录")}</summary>{p.items.map((i:any)=><p key={i.key}>{t(i.term)} · {t(i.source.title)} {t("· 抓取时间")}{t(i.source.fetchedAt)} · <a href={i.source.url} target="_blank" rel="noreferrer">{t("官方正文")}</a></p>)}</details></details>)}</>:<p className="muted">{t("正在读取词汇学习情况…")}</p>}</section>;
}
