import {Bilingual,WritingMode} from './writing-settings';
const pair=(zh:string,en:string):Bilingual=>({zh,en});
export const rubricSources=[
 {id:'ielts-descriptors',kind:'official',title:'IELTS Writing Band Descriptors, May 2023',url:'https://ielts.org/cdn/ielts-guides/ielts-writing-band-descriptors.pdf'},
 {id:'ielts-format',kind:'official',title:'IELTS Academic Writing format',url:'https://ielts.org/take-a-test/test-types/ielts-academic-test/ielts-academic-format-writing'},
 {id:'gre-issue',kind:'official',title:'ETS GRE Analyze an Issue scoring guide',url:'https://www.ets.org/gre/test-takers/general-test/prepare/content/analytical-writing/scoring.html'},
 {id:'toefl-discussion',kind:'official',title:'ETS Writing Scoring Guide: Academic Discussion',url:'https://www.ets.org/content/dam/ets-org/pdfs/toefl/writing-rubrics.pdf'},
 {id:'task1-research',kind:'research',title:'Task design in IELTS Academic Writing Task 1',url:'https://ielts.org/researchers/our-research/research-reports/task-design-in-ielts-academic-writing-task-1-the-effect-of-quantity-and-manner-of-presentation-of-information-on-candidate-writing'},
 {id:'feedback-research',kind:'research',title:'Learners’ processing, uptake, and retention of corrective feedback on writing',url:'https://doi.org/10.1017/S0272263109990532'},
 {id:'task1-teaching',kind:'teaching',title:'British Council Academic Task 1 lesson plans',url:'https://takeielts.britishcouncil.org/teach-ielts/teaching-resources/lesson-plans-writing'}
];
export const rubricVersion='2026-10-02-v3';
export const criterionNames:Record<string,Bilingual>={
 task:pair('任务完成 / 回应','Task achievement / response'),coherence:pair('连贯与衔接','Coherence and cohesion'),lexis:pair('词汇资源','Lexical resource'),grammar:pair('语法范围与准确性','Grammatical range and accuracy'),
 analysis:pair('观点与分析','Position and analysis'),support:pair('理由与例证','Reasons and support'),organization:pair('组织与推进','Organization'),language:pair('表达范围与清晰度','Language and clarity'),development:pair('相关性与展开','Relevance and development'),accuracy:pair('语言准确性','Language accuracy')
};
export function rubricFor(mode:WritingMode){
 const ielts=mode.startsWith('ielts');
 return {version:rubricVersion,mode,scale:ielts?9:mode==='gre_issue'?6:5,scoring:ielts?'four_equal_criteria':'holistic',criterionIds:ielts?['task','coherence','lexis','grammar']:mode==='gre_issue'?['analysis','support','organization','language']:['development','organization','language','accuracy'],
  rules:mode==='ielts_task1'?
   'Academic visual description. Assess overview, selected key features, relevant comparisons and accurate support from the image; organize information logically; judge vocabulary and grammar for appropriate, precise use. Minimum 150 words. Never infer causes or figures absent from the visual. Missing an overview or misreporting a central feature can materially affect task achievement.':mode==='ielts_task2'?
   'Address all parts of the prompt, maintain a developed position, extend ideas with relevant support, sequence them coherently and use accurate, appropriate language. Minimum 250 words. Judge all four criteria equally for this task; do not treat this single-task estimate as an overall IELTS Writing section score.':mode==='gre_issue'?
   'Judge the response holistically on the ETS Issue scale. Stronger responses develop a nuanced position with convincing reasons or examples, sustain focused logical organization and communicate precisely. Weaker responses have limited development, organization or clarity. The planning fields are teaching aids, not a mandated ETS essay structure. No official fixed minimum word count.':
   'Apply the ETS Academic Discussion response rubric, 0–5: relevance to the discussion, developed explanations or examples, varied and appropriate language, and control of errors. 5: effective, well-developed and clear; 4: generally clear with adequate support; 3: partial development or noticeable language limitations; 2–1: limited development and frequent obscuring errors; 0: blank, irrelevant, copied or non-English. This is a task estimate, not the 1–6 TOEFL section score. If classmates’ posts are absent, note the contextual limitation.',
  bandAnchors:ielts?{task1:'7: clear overview, relevant key features; 6: some overview and relevant features, uneven selection; 5: weak overview or detail focus.',task2:'7: clear developed position and supported main ideas; 6: relevant position, uneven development; 5: incomplete response or insufficient support.',coherence:'7: clear progression with generally effective paragraphs; 6: generally coherent with mechanical links; 5: weak progression or organization.',lexis:'7: flexible, precise vocabulary with occasional errors; 6: adequate range, imperfect precision; 5: limited range and noticeable inaccuracies.',grammar:'7: varied structures, frequent error-free sentences; 6: simple/complex mix with errors rarely blocking meaning; 5: restricted structures and frequent errors.',range:'8–9 require increasingly sustained control and full development; 4 and below show increasingly limited task coverage, organization and language. Apply descriptors to evidence, never average imagined subskills.'}:mode==='gre_issue'?{'6':'insightful and well-supported, effective organization, precise fluent language','5':'thoughtful, developed, logically organized, clear language with minor errors','4':'competent analysis and adequate support; generally organized and clear','3':'limited analysis/support or organization; language weaknesses may reduce clarity','2':'seriously weak analysis or clarity','1':'fundamental deficiencies','0':'off-topic, copied, non-English or blank response'}:null,
  sourceIds:ielts?['ielts-descriptors','ielts-format',...(mode==='ielts_task1'?['task1-research','task1-teaching']:[])]:[mode==='gre_issue'?'gre-issue':'toefl-discussion'],
  learningPolicy:'Priority is a WRTBU teaching interpretation, not an official binary label. Changes affecting task coverage, reasoning, data truth, coherence or meaning are important. Accurate alternatives that only refine style or range are optional. Uncommon vocabulary is helpful only when natural and precise. Learners explain their choice; accepting the sample is not required. Feedback research informs the interaction design, not numerical scoring.'};
}
export const changeCategories=['task_coverage','reasoning_gap','data_accuracy','coherence_break','meaning_grammar','word_accuracy','precision','style'] as const;
export type ChangeCategory=typeof changeCategories[number];
export const changePriority=(category:ChangeCategory)=>['precision','style'].includes(category)?'optional':'important';
export const categoryNames:Record<ChangeCategory,Bilingual>={task_coverage:pair('任务覆盖','Task coverage'),reasoning_gap:pair('论证缺口','Reasoning gap'),data_accuracy:pair('数据准确性','Data accuracy'),coherence_break:pair('逻辑衔接','Coherence'),meaning_grammar:pair('影响理解的语法','Grammar affecting meaning'),word_accuracy:pair('用词准确性','Word accuracy'),precision:pair('表达精度','Precision'),style:pair('表达选择','Style choice')};
